CREATE TABLE [dbo].[Credentials]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(50) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NOT NULL UNIQUE,
	Password VARCHAR(255) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NOT NULL,
	Email VARCHAR(50) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NOT NULL,
)
